# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/soso2/OneDrive/Bureau/taf/Tek2/Jam/EpitechJamYinYang

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/soso2/OneDrive/Bureau/taf/Tek2/Jam/EpitechJamYinYang

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/soso2/OneDrive/Bureau/taf/Tek2/Jam/EpitechJamYinYang/CMakeFiles /mnt/c/Users/soso2/OneDrive/Bureau/taf/Tek2/Jam/EpitechJamYinYang/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/soso2/OneDrive/Bureau/taf/Tek2/Jam/EpitechJamYinYang/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yinyangClash

# Build rule for target.
yinyangClash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yinyangClash
.PHONY : yinyangClash

# fast build rule for target.
yinyangClash/fast:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/build
.PHONY : yinyangClash/fast

src/animation/Animation.o: src/animation/Animation.cpp.o

.PHONY : src/animation/Animation.o

# target to build an object file
src/animation/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/animation/Animation.cpp.o
.PHONY : src/animation/Animation.cpp.o

src/animation/Animation.i: src/animation/Animation.cpp.i

.PHONY : src/animation/Animation.i

# target to preprocess a source file
src/animation/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/animation/Animation.cpp.i
.PHONY : src/animation/Animation.cpp.i

src/animation/Animation.s: src/animation/Animation.cpp.s

.PHONY : src/animation/Animation.s

# target to generate assembly for a file
src/animation/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/animation/Animation.cpp.s
.PHONY : src/animation/Animation.cpp.s

src/clock/Clock.o: src/clock/Clock.cpp.o

.PHONY : src/clock/Clock.o

# target to build an object file
src/clock/Clock.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/clock/Clock.cpp.o
.PHONY : src/clock/Clock.cpp.o

src/clock/Clock.i: src/clock/Clock.cpp.i

.PHONY : src/clock/Clock.i

# target to preprocess a source file
src/clock/Clock.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/clock/Clock.cpp.i
.PHONY : src/clock/Clock.cpp.i

src/clock/Clock.s: src/clock/Clock.cpp.s

.PHONY : src/clock/Clock.s

# target to generate assembly for a file
src/clock/Clock.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/clock/Clock.cpp.s
.PHONY : src/clock/Clock.cpp.s

src/cursor/Cursor.o: src/cursor/Cursor.cpp.o

.PHONY : src/cursor/Cursor.o

# target to build an object file
src/cursor/Cursor.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/cursor/Cursor.cpp.o
.PHONY : src/cursor/Cursor.cpp.o

src/cursor/Cursor.i: src/cursor/Cursor.cpp.i

.PHONY : src/cursor/Cursor.i

# target to preprocess a source file
src/cursor/Cursor.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/cursor/Cursor.cpp.i
.PHONY : src/cursor/Cursor.cpp.i

src/cursor/Cursor.s: src/cursor/Cursor.cpp.s

.PHONY : src/cursor/Cursor.s

# target to generate assembly for a file
src/cursor/Cursor.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/cursor/Cursor.cpp.s
.PHONY : src/cursor/Cursor.cpp.s

src/engine/Engine.o: src/engine/Engine.cpp.o

.PHONY : src/engine/Engine.o

# target to build an object file
src/engine/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/engine/Engine.cpp.o
.PHONY : src/engine/Engine.cpp.o

src/engine/Engine.i: src/engine/Engine.cpp.i

.PHONY : src/engine/Engine.i

# target to preprocess a source file
src/engine/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/engine/Engine.cpp.i
.PHONY : src/engine/Engine.cpp.i

src/engine/Engine.s: src/engine/Engine.cpp.s

.PHONY : src/engine/Engine.s

# target to generate assembly for a file
src/engine/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/engine/Engine.cpp.s
.PHONY : src/engine/Engine.cpp.s

src/helper/info/info.o: src/helper/info/info.cpp.o

.PHONY : src/helper/info/info.o

# target to build an object file
src/helper/info/info.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/helper/info/info.cpp.o
.PHONY : src/helper/info/info.cpp.o

src/helper/info/info.i: src/helper/info/info.cpp.i

.PHONY : src/helper/info/info.i

# target to preprocess a source file
src/helper/info/info.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/helper/info/info.cpp.i
.PHONY : src/helper/info/info.cpp.i

src/helper/info/info.s: src/helper/info/info.cpp.s

.PHONY : src/helper/info/info.s

# target to generate assembly for a file
src/helper/info/info.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/helper/info/info.cpp.s
.PHONY : src/helper/info/info.cpp.s

src/helper/math/math.o: src/helper/math/math.cpp.o

.PHONY : src/helper/math/math.o

# target to build an object file
src/helper/math/math.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/helper/math/math.cpp.o
.PHONY : src/helper/math/math.cpp.o

src/helper/math/math.i: src/helper/math/math.cpp.i

.PHONY : src/helper/math/math.i

# target to preprocess a source file
src/helper/math/math.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/helper/math/math.cpp.i
.PHONY : src/helper/math/math.cpp.i

src/helper/math/math.s: src/helper/math/math.cpp.s

.PHONY : src/helper/math/math.s

# target to generate assembly for a file
src/helper/math/math.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/helper/math/math.cpp.s
.PHONY : src/helper/math/math.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/rectangle/Box.o: src/rectangle/Box.cpp.o

.PHONY : src/rectangle/Box.o

# target to build an object file
src/rectangle/Box.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/rectangle/Box.cpp.o
.PHONY : src/rectangle/Box.cpp.o

src/rectangle/Box.i: src/rectangle/Box.cpp.i

.PHONY : src/rectangle/Box.i

# target to preprocess a source file
src/rectangle/Box.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/rectangle/Box.cpp.i
.PHONY : src/rectangle/Box.cpp.i

src/rectangle/Box.s: src/rectangle/Box.cpp.s

.PHONY : src/rectangle/Box.s

# target to generate assembly for a file
src/rectangle/Box.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/rectangle/Box.cpp.s
.PHONY : src/rectangle/Box.cpp.s

src/resource_manager/ResourceManager.o: src/resource_manager/ResourceManager.cpp.o

.PHONY : src/resource_manager/ResourceManager.o

# target to build an object file
src/resource_manager/ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/resource_manager/ResourceManager.cpp.o
.PHONY : src/resource_manager/ResourceManager.cpp.o

src/resource_manager/ResourceManager.i: src/resource_manager/ResourceManager.cpp.i

.PHONY : src/resource_manager/ResourceManager.i

# target to preprocess a source file
src/resource_manager/ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/resource_manager/ResourceManager.cpp.i
.PHONY : src/resource_manager/ResourceManager.cpp.i

src/resource_manager/ResourceManager.s: src/resource_manager/ResourceManager.cpp.s

.PHONY : src/resource_manager/ResourceManager.s

# target to generate assembly for a file
src/resource_manager/ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/resource_manager/ResourceManager.cpp.s
.PHONY : src/resource_manager/ResourceManager.cpp.s

src/scene/menu/Menu.o: src/scene/menu/Menu.cpp.o

.PHONY : src/scene/menu/Menu.o

# target to build an object file
src/scene/menu/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/scene/menu/Menu.cpp.o
.PHONY : src/scene/menu/Menu.cpp.o

src/scene/menu/Menu.i: src/scene/menu/Menu.cpp.i

.PHONY : src/scene/menu/Menu.i

# target to preprocess a source file
src/scene/menu/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/scene/menu/Menu.cpp.i
.PHONY : src/scene/menu/Menu.cpp.i

src/scene/menu/Menu.s: src/scene/menu/Menu.cpp.s

.PHONY : src/scene/menu/Menu.s

# target to generate assembly for a file
src/scene/menu/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/scene/menu/Menu.cpp.s
.PHONY : src/scene/menu/Menu.cpp.s

src/scene/scene_manager/SceneManager.o: src/scene/scene_manager/SceneManager.cpp.o

.PHONY : src/scene/scene_manager/SceneManager.o

# target to build an object file
src/scene/scene_manager/SceneManager.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/scene/scene_manager/SceneManager.cpp.o
.PHONY : src/scene/scene_manager/SceneManager.cpp.o

src/scene/scene_manager/SceneManager.i: src/scene/scene_manager/SceneManager.cpp.i

.PHONY : src/scene/scene_manager/SceneManager.i

# target to preprocess a source file
src/scene/scene_manager/SceneManager.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/scene/scene_manager/SceneManager.cpp.i
.PHONY : src/scene/scene_manager/SceneManager.cpp.i

src/scene/scene_manager/SceneManager.s: src/scene/scene_manager/SceneManager.cpp.s

.PHONY : src/scene/scene_manager/SceneManager.s

# target to generate assembly for a file
src/scene/scene_manager/SceneManager.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/scene/scene_manager/SceneManager.cpp.s
.PHONY : src/scene/scene_manager/SceneManager.cpp.s

src/settings/Settings.o: src/settings/Settings.cpp.o

.PHONY : src/settings/Settings.o

# target to build an object file
src/settings/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/settings/Settings.cpp.o
.PHONY : src/settings/Settings.cpp.o

src/settings/Settings.i: src/settings/Settings.cpp.i

.PHONY : src/settings/Settings.i

# target to preprocess a source file
src/settings/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/settings/Settings.cpp.i
.PHONY : src/settings/Settings.cpp.i

src/settings/Settings.s: src/settings/Settings.cpp.s

.PHONY : src/settings/Settings.s

# target to generate assembly for a file
src/settings/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/settings/Settings.cpp.s
.PHONY : src/settings/Settings.cpp.s

src/shader/GreyScale.o: src/shader/GreyScale.cpp.o

.PHONY : src/shader/GreyScale.o

# target to build an object file
src/shader/GreyScale.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/shader/GreyScale.cpp.o
.PHONY : src/shader/GreyScale.cpp.o

src/shader/GreyScale.i: src/shader/GreyScale.cpp.i

.PHONY : src/shader/GreyScale.i

# target to preprocess a source file
src/shader/GreyScale.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/shader/GreyScale.cpp.i
.PHONY : src/shader/GreyScale.cpp.i

src/shader/GreyScale.s: src/shader/GreyScale.cpp.s

.PHONY : src/shader/GreyScale.s

# target to generate assembly for a file
src/shader/GreyScale.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/shader/GreyScale.cpp.s
.PHONY : src/shader/GreyScale.cpp.s

src/ui/Widget.o: src/ui/Widget.cpp.o

.PHONY : src/ui/Widget.o

# target to build an object file
src/ui/Widget.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/Widget.cpp.o
.PHONY : src/ui/Widget.cpp.o

src/ui/Widget.i: src/ui/Widget.cpp.i

.PHONY : src/ui/Widget.i

# target to preprocess a source file
src/ui/Widget.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/Widget.cpp.i
.PHONY : src/ui/Widget.cpp.i

src/ui/Widget.s: src/ui/Widget.cpp.s

.PHONY : src/ui/Widget.s

# target to generate assembly for a file
src/ui/Widget.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/Widget.cpp.s
.PHONY : src/ui/Widget.cpp.s

src/ui/button/Button.o: src/ui/button/Button.cpp.o

.PHONY : src/ui/button/Button.o

# target to build an object file
src/ui/button/Button.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/button/Button.cpp.o
.PHONY : src/ui/button/Button.cpp.o

src/ui/button/Button.i: src/ui/button/Button.cpp.i

.PHONY : src/ui/button/Button.i

# target to preprocess a source file
src/ui/button/Button.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/button/Button.cpp.i
.PHONY : src/ui/button/Button.cpp.i

src/ui/button/Button.s: src/ui/button/Button.cpp.s

.PHONY : src/ui/button/Button.s

# target to generate assembly for a file
src/ui/button/Button.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/button/Button.cpp.s
.PHONY : src/ui/button/Button.cpp.s

src/ui/slider/Slider.o: src/ui/slider/Slider.cpp.o

.PHONY : src/ui/slider/Slider.o

# target to build an object file
src/ui/slider/Slider.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/slider/Slider.cpp.o
.PHONY : src/ui/slider/Slider.cpp.o

src/ui/slider/Slider.i: src/ui/slider/Slider.cpp.i

.PHONY : src/ui/slider/Slider.i

# target to preprocess a source file
src/ui/slider/Slider.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/slider/Slider.cpp.i
.PHONY : src/ui/slider/Slider.cpp.i

src/ui/slider/Slider.s: src/ui/slider/Slider.cpp.s

.PHONY : src/ui/slider/Slider.s

# target to generate assembly for a file
src/ui/slider/Slider.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/slider/Slider.cpp.s
.PHONY : src/ui/slider/Slider.cpp.s

src/ui/text/UIText.o: src/ui/text/UIText.cpp.o

.PHONY : src/ui/text/UIText.o

# target to build an object file
src/ui/text/UIText.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/text/UIText.cpp.o
.PHONY : src/ui/text/UIText.cpp.o

src/ui/text/UIText.i: src/ui/text/UIText.cpp.i

.PHONY : src/ui/text/UIText.i

# target to preprocess a source file
src/ui/text/UIText.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/text/UIText.cpp.i
.PHONY : src/ui/text/UIText.cpp.i

src/ui/text/UIText.s: src/ui/text/UIText.cpp.s

.PHONY : src/ui/text/UIText.s

# target to generate assembly for a file
src/ui/text/UIText.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/text/UIText.cpp.s
.PHONY : src/ui/text/UIText.cpp.s

src/ui/tickbox/TickBox.o: src/ui/tickbox/TickBox.cpp.o

.PHONY : src/ui/tickbox/TickBox.o

# target to build an object file
src/ui/tickbox/TickBox.cpp.o:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/tickbox/TickBox.cpp.o
.PHONY : src/ui/tickbox/TickBox.cpp.o

src/ui/tickbox/TickBox.i: src/ui/tickbox/TickBox.cpp.i

.PHONY : src/ui/tickbox/TickBox.i

# target to preprocess a source file
src/ui/tickbox/TickBox.cpp.i:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/tickbox/TickBox.cpp.i
.PHONY : src/ui/tickbox/TickBox.cpp.i

src/ui/tickbox/TickBox.s: src/ui/tickbox/TickBox.cpp.s

.PHONY : src/ui/tickbox/TickBox.s

# target to generate assembly for a file
src/ui/tickbox/TickBox.cpp.s:
	$(MAKE) -f CMakeFiles/yinyangClash.dir/build.make CMakeFiles/yinyangClash.dir/src/ui/tickbox/TickBox.cpp.s
.PHONY : src/ui/tickbox/TickBox.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... yinyangClash"
	@echo "... src/animation/Animation.o"
	@echo "... src/animation/Animation.i"
	@echo "... src/animation/Animation.s"
	@echo "... src/clock/Clock.o"
	@echo "... src/clock/Clock.i"
	@echo "... src/clock/Clock.s"
	@echo "... src/cursor/Cursor.o"
	@echo "... src/cursor/Cursor.i"
	@echo "... src/cursor/Cursor.s"
	@echo "... src/engine/Engine.o"
	@echo "... src/engine/Engine.i"
	@echo "... src/engine/Engine.s"
	@echo "... src/helper/info/info.o"
	@echo "... src/helper/info/info.i"
	@echo "... src/helper/info/info.s"
	@echo "... src/helper/math/math.o"
	@echo "... src/helper/math/math.i"
	@echo "... src/helper/math/math.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/rectangle/Box.o"
	@echo "... src/rectangle/Box.i"
	@echo "... src/rectangle/Box.s"
	@echo "... src/resource_manager/ResourceManager.o"
	@echo "... src/resource_manager/ResourceManager.i"
	@echo "... src/resource_manager/ResourceManager.s"
	@echo "... src/scene/menu/Menu.o"
	@echo "... src/scene/menu/Menu.i"
	@echo "... src/scene/menu/Menu.s"
	@echo "... src/scene/scene_manager/SceneManager.o"
	@echo "... src/scene/scene_manager/SceneManager.i"
	@echo "... src/scene/scene_manager/SceneManager.s"
	@echo "... src/settings/Settings.o"
	@echo "... src/settings/Settings.i"
	@echo "... src/settings/Settings.s"
	@echo "... src/shader/GreyScale.o"
	@echo "... src/shader/GreyScale.i"
	@echo "... src/shader/GreyScale.s"
	@echo "... src/ui/Widget.o"
	@echo "... src/ui/Widget.i"
	@echo "... src/ui/Widget.s"
	@echo "... src/ui/button/Button.o"
	@echo "... src/ui/button/Button.i"
	@echo "... src/ui/button/Button.s"
	@echo "... src/ui/slider/Slider.o"
	@echo "... src/ui/slider/Slider.i"
	@echo "... src/ui/slider/Slider.s"
	@echo "... src/ui/text/UIText.o"
	@echo "... src/ui/text/UIText.i"
	@echo "... src/ui/text/UIText.s"
	@echo "... src/ui/tickbox/TickBox.o"
	@echo "... src/ui/tickbox/TickBox.i"
	@echo "... src/ui/tickbox/TickBox.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

